version: '2.4' # The last version of Docker compose file format that directly supports mem_limit and cpus
services: 
  counter-service:
    container_name: counter-service-project-cont  
    image: 127214174680.dkr.ecr.eu-north-1.amazonaws.com/my_project_ecr:latest
    volumes:
      - ./data:/data:rw
    ports:
    - "80:8080"
    restart: always
    mem_limit: 256M
    cpus: 0.5